name: Build-armhf

on:
  release:
    types:
      - created
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: save working directory in variable 'DIR'
        run: echo "DIR=$(pwd)" >> $GITHUB_ENV

      - name: setup node
        uses: actions/setup-node@v2
        with:
         node-version: '14'

      - name: clone repo and checkout latest release
        run: |
          cd $DIR
          rm -rf youtube-dl-gui
          git clone https://github.com/jely2002/youtube-dl-gui
          cd youtube-dl-gui
          
      - name: Build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd $DIR/youtube-dl-gui
          npm install
          npx electron-builder --linux --armv7l
          echo "DEB=$(basename dist/*armv7l.AppImage)" >> $GITHUB_ENV 
          
      - name: Upload to release
        uses: docker://gacts/upload-to-release:latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: '${{ env.DIR }}/youtube-dl-gui/dist/${{ env.DEB }}'
          type: 'application/x-debian-package'
